apiversion: app/v1
kind: Deployment
metadata:
  labels:
    apps: mariadb
    name: mariadb-deploy
spac:
  replicas: 1
  selector:
    matchLables:
      app: mariadb
    spec:
      containers:
      - name: mariadb
        image: docker.io/mariadb:10.4
        ports:
        - containerPort: 3306
          protocal: TCP          
