kind: Deployment
apiVersion: apps/v1
metadata:
  name: ebay-app
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      app: ebay
  template:
    metadata:
      labels:
        environment: dev
        app: ebay
    spec:
      volumes:
      - name: volume1
        hostPath:
          path: /mnt/data
      - name: volume2
        hostPath:
          path: /mnt/data
      containers:
      - name: container1-nginx
        image: nginx
        volumeMounts:
        - name: volume1
          mountPath: "/var/nginx-data"
      - name: container2-tomcat
        image: tomcat
        volumeMounts:  # ✅ Corrected indentation
        - name: volume2
          mountPath: "/var/tomcat-data"

