kind: Deployment
apiVersion: apps/v1
metadata:
  name: ebay-app
spec:
  replicas: 3
  selector:
    matchLabels:  # ✅ Corrected indentation
      environment: dev
      app: ebay
  template:
    metadata:
      labels:
        environment: dev
        app: ebay
    spec:
      volumes:
      - name: volume
        hostPath:
          path: /mnt/data
      containers:
      - name: container1-nginx
        image: nginx
        volumeMounts:
        - name: volume  # ✅ Corrected indentation
          mountPath: "/var/nginx-data"
      - name: container2-tomcat
        image: tomcat

